/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-parking`; params?: Router.UnknownInputParams; } | { pathname: `/edit-parking`; params?: Router.UnknownInputParams; } | { pathname: `/rent-parking`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-parking` | `/my-parking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-rentals` | `/my-rentals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-parking`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-parking`; params?: Router.UnknownOutputParams; } | { pathname: `/rent-parking`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-parking` | `/my-parking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/my-rentals` | `/my-rentals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-parking${`?${string}` | `#${string}` | ''}` | `/edit-parking${`?${string}` | `#${string}` | ''}` | `/rent-parking${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-parking${`?${string}` | `#${string}` | ''}` | `/my-parking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/my-rentals${`?${string}` | `#${string}` | ''}` | `/my-rentals${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-parking`; params?: Router.UnknownInputParams; } | { pathname: `/edit-parking`; params?: Router.UnknownInputParams; } | { pathname: `/rent-parking`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-parking` | `/my-parking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/my-rentals` | `/my-rentals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; };
    }
  }
}
